package com.safetech.otshield.repository;

import com.safetech.otshield.model.NIS2ComplianceReport;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for NIS2ComplianceReport entity
 * Provides database operations and custom queries
 */
@Repository
public interface NIS2ComplianceReportRepository extends JpaRepository<NIS2ComplianceReport, String> {

    // Basic CRUD operations
    Optional<NIS2ComplianceReport> findByTitle(String title);
    List<NIS2ComplianceReport> findByTitleContainingIgnoreCase(String title);
    List<NIS2ComplianceReport> findByDescriptionContainingIgnoreCase(String description);

    // Type-based queries
    List<NIS2ComplianceReport> findByReportType(NIS2ComplianceReport.ReportType reportType);
    Page<NIS2ComplianceReport> findByReportType(Pageable pageable, NIS2ComplianceReport.ReportType reportType);

    // Status-based queries
    List<NIS2ComplianceReport> findByStatus(NIS2ComplianceReport.ReportStatus status);
    Page<NIS2ComplianceReport> findByStatus(Pageable pageable, NIS2ComplianceReport.ReportStatus status);

    // Date-based queries
    List<NIS2ComplianceReport> findByGeneratedAtBetween(LocalDateTime startDate, LocalDateTime endDate);
    List<NIS2ComplianceReport> findByReportPeriodStartBetween(LocalDateTime startDate, LocalDateTime endDate);
    List<NIS2ComplianceReport> findByReportPeriodEndBetween(LocalDateTime startDate, LocalDateTime endDate);

    // Generated by queries
    List<NIS2ComplianceReport> findByGeneratedBy(String generatedBy);
    List<NIS2ComplianceReport> findByApprovedBy(String approvedBy);

    // Score-based queries
    List<NIS2ComplianceReport> findByOverallComplianceScoreGreaterThan(Integer score);
    List<NIS2ComplianceReport> findByOverallComplianceScoreLessThan(Integer score);
    List<NIS2ComplianceReport> findByOverallComplianceScoreBetween(Integer minScore, Integer maxScore);

    // Tag-based queries
    List<NIS2ComplianceReport> findByTagsContaining(String tag);

    // Complex queries
    @Query("SELECT r FROM NIS2ComplianceReport r WHERE " +
           "(:reportType IS NULL OR r.reportType = :reportType) AND " +
           "(:status IS NULL OR r.status = :status) AND " +
           "(:generatedBy IS NULL OR r.generatedBy = :generatedBy)")
    Page<NIS2ComplianceReport> findByFilters(
            @Param("reportType") NIS2ComplianceReport.ReportType reportType,
            @Param("status") NIS2ComplianceReport.ReportStatus status,
            @Param("generatedBy") String generatedBy,
            Pageable pageable);

    @Query("SELECT r FROM NIS2ComplianceReport r WHERE " +
           "r.title LIKE %:searchTerm% OR " +
           "r.description LIKE %:searchTerm%")
    Page<NIS2ComplianceReport> searchByTerm(@Param("searchTerm") String searchTerm, Pageable pageable);

    // Statistics queries
    @Query("SELECT COUNT(r) FROM NIS2ComplianceReport r WHERE r.status = :status")
    Long countByStatus(@Param("status") NIS2ComplianceReport.ReportStatus status);

    @Query("SELECT COUNT(r) FROM NIS2ComplianceReport r WHERE r.reportType = :reportType")
    Long countByReportType(@Param("reportType") NIS2ComplianceReport.ReportType reportType);

    @Query("SELECT AVG(r.overallComplianceScore) FROM NIS2ComplianceReport r WHERE r.overallComplianceScore IS NOT NULL")
    Double getAverageComplianceScore();

    @Query("SELECT AVG(r.overallComplianceScore) FROM NIS2ComplianceReport r WHERE r.overallComplianceScore IS NOT NULL AND r.generatedAt BETWEEN :startDate AND :endDate")
    Double getAverageComplianceScoreBetween(@Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate);

    // Recent reports
    @Query("SELECT r FROM NIS2ComplianceReport r WHERE r.generatedAt >= :since ORDER BY r.generatedAt DESC")
    List<NIS2ComplianceReport> findRecentReports(@Param("since") LocalDateTime since);

    // Reports by compliance score range
    @Query("SELECT r FROM NIS2ComplianceReport r WHERE r.overallComplianceScore >= :minScore AND r.overallComplianceScore <= :maxScore")
    List<NIS2ComplianceReport> findReportsByComplianceScoreRange(
            @Param("minScore") Integer minScore,
            @Param("maxScore") Integer maxScore);

    // Reports with critical findings
    @Query("SELECT r FROM NIS2ComplianceReport r WHERE r.criticalFindingsCount > 0 ORDER BY r.criticalFindingsCount DESC")
    List<NIS2ComplianceReport> findReportsWithCriticalFindings();

    // Reports by period
    @Query("SELECT r FROM NIS2ComplianceReport r WHERE r.reportPeriodStart >= :startDate AND r.reportPeriodEnd <= :endDate")
    List<NIS2ComplianceReport> findReportsByPeriod(
            @Param("startDate") LocalDateTime startDate,
            @Param("endDate") LocalDateTime endDate);

    // Latest report by type
    @Query("SELECT r FROM NIS2ComplianceReport r WHERE r.reportType = :reportType ORDER BY r.generatedAt DESC")
    List<NIS2ComplianceReport> findLatestReportsByType(@Param("reportType") NIS2ComplianceReport.ReportType reportType, Pageable pageable);
} 